server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter
        - id: account-service-route
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - JwtAuthenticationFilter
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: wYsyEr6p1G0fUkIlCNF8zCKL5KLdlYu1iavEgwWsiLyKfZX91h4SrMm24gse6wuk #dev
  accessTokenExpirationTime: 900000  # 15 minutes in milliseconds (900000 ms)
  refreshTokenExpirationTime: 604800000  # 30 days in milliseconds (2592000000 ms)