spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank_System
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  #    hikari:
  #      maximum-pool-size: 10  # Development DB connection pool size
  jpa:
    hibernate:
      ddl-auto: update  # In development, auto-create tables
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  consumer:
    group-id: user-service-group
  topic:
    user-created: user-created

logging:
  level:
    js.project.auth_service: DEBUG