spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank_System
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  #    hikari:
  #      maximum-pool-size: 10  # Development DB connection pool size
  jpa:
    hibernate:
      ddl-auto: update  # In development, auto-create tables
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    js.project.auth_service: DEBUG